networks:
  default:
    external:
      name: roboshop

services:
  # docker run -d --name mongodb --network=roboshop mongodb:1
  mongodb:
    container_name: mongodb
    image: mongodb:01v

  catalouge:
    container_name: catalouge
    image: catalouge:01v
    depends_on:
    - mongodb
    
  web:
    ports:
    - "80:80"
    container_name: web
    image: web:01v
    depends_on:
    - catalouge