networks:
  default:
    external:
      name: roboshop

services:
  mongodb:
    image: mongodb:01v
    container_name: mongodb
    

  catalouge:
    container_name: catalouge
    image: catalouge:01v
    depends_on:
    - mongodb

  web:
    ports:
    - "80:80"
    container_name: web
    image: web:01v
    depends_on:
    - catalouge

